// controllers/catalogsController.js

// Sample data for catalogs
const occupations = [
  { id: 1, description: 'ABARROTERO', risk: 'NORMAL' },
  { id: 2, description: 'ABOGADO', risk: 'NORMAL' },
  { id: 3, description: 'ACOMODADOR DE MERCANCÍA EN TIENDA', risk: 'NORMAL' },
  { id: 4, description: 'ACTOR', risk: 'NORMAL' },
  { id: 5, description: 'ACUPUNTURISTA', risk: 'NORMAL' },
  { id: 6, description: 'ADMINISTRATIVO', risk: 'NORMAL' },
  { id: 7, description: 'AFANADOR', risk: 'NORMAL' },
  { id: 8, description: 'AGENTE DE SEGURIDAD', risk: 'SUBNORMAL' },
  { id: 9, description: 'AGENTE DE VENTAS', risk: 'NORMAL' },
  { id: 10, description: 'AGENTE INVESTIGADOR (JUDICIAL)', risk: 'SUBNORMAL' },
  { id: 11, description: 'AGENTE MINISTERIO PÚBLICO ESTATAL', risk: 'SUBNORMAL' },
  { id: 12, description: 'AGRICULTOR', risk: 'NORMAL' },
  { id: 13, description: 'ALBAÑIL', risk: 'SUBNORMAL' },
  { id: 14, description: 'ALCANTARILLADO', risk: 'NORMAL' },
  { id: 15, description: 'ALMACENISTA REGISTRO DE ENTRADA Y SALIDA DE MERCANCIA', risk: 'NORMAL' },
  { id: 16, description: 'ALUMINERO O VIDRIERO', risk: 'NORMAL' },
  { id: 17, description: 'ANALISTA ADMINISTRATIVO', risk: 'NORMAL' },
  { id: 18, description: 'ANESTESIÓLOGO', risk: 'SUBNORMAL' },
  { id: 19, description: 'ARCHIVISTA', risk: 'NORMAL' },
  { id: 20, description: 'ARQUITECTO', risk: 'NORMAL' },
  { id: 21, description: 'ASESOR COMERCIAL', risk: 'NORMAL' },
  { id: 22, description: 'ASESOR FINANCIERO', risk: 'NORMAL' },
  { id: 23, description: 'ASISTENTE ADMINISTRATIVO', risk: 'NORMAL' },
  { id: 24, description: 'ASISTENTE DE COCINA', risk: 'SUBNORMAL' },
  { id: 25, description: 'ATENCIÓN A CLIENTES', risk: 'NORMAL' },
  { id: 26, description: 'AUDITOR', risk: 'NORMAL' },
  { id: 27, description: 'AUXILIAR EN ABARROTES', risk: 'NORMAL' },
  { id: 28, description: 'AUXILIAR EN ALMACÉN CARGA DE MERCANCIA', risk: 'NORMAL' },
  { id: 29, description: 'AUXILIAR EN BODEGA CARGA DE MERCANCIA', risk: 'NORMAL' },
  { id: 30, description: 'AUXILIAR EN CARNICERÍA', risk: 'NORMAL' },
  { id: 31, description: 'AUXILIAR EN COCINA', risk: 'SUBNORMAL' },
  { id: 32, description: 'AUXILIAR EN FRUTERÍA', risk: 'NORMAL' },
  { id: 33, description: 'AUXILIAR EN INTENDENCIA', risk: 'SUBNORMAL' },
  { id: 34, description: 'AUXILIAR EN LIMPIEZA', risk: 'SUBNORMAL' },
  { id: 35, description: 'AUXILIAR EN PANADERÍA', risk: 'NORMAL' },
  { id: 36, description: 'AUXILIAR EN SALCHICHONERIA', risk: 'NORMAL' },
  { id: 37, description: 'AUXILIAR EN SERVICIOS URBANOS', risk: 'NORMAL' },
  { id: 38, description: 'AUXILIAR EN TALLER MECÁNICO', risk: 'NORMAL' },
  { id: 39, description: 'AZAFATA/SOBRECARGO', risk: 'SUBNORMAL' },
  { id: 40, description: 'BACHEO', risk: 'NORMAL' },
  { id: 41, description: 'BARRENDERO', risk: 'NORMAL' },
  { id: 42, description: 'BIBLIOTECARIO', risk: 'NORMAL' },
  { id: 43, description: 'BIÓLOGO', risk: 'SUBNORMAL' },
  { id: 44, description: 'BOMBERO', risk: 'SUBNORMAL' },
  { id: 45, description: 'BRIGADISTA', risk: 'SUBNORMAL' },
  { id: 46, description: 'CADENERO', risk: 'NORMAL' },
  { id: 47, description: 'CAMILLERO', risk: 'SUBNORMAL' },
  { id: 48, description: 'CAMPESINO', risk: 'NORMAL' },
  { id: 49, description: 'CANTANTE', risk: 'NORMAL' },
  { id: 50, description: 'CANTINERO', risk: 'NORMAL' },
  { id: 51, description: 'CAPACITADOR', risk: 'NORMAL' },
  { id: 52, description: 'CAPITÁN DE MESEROS', risk: 'NORMAL' },
  { id: 53, description: 'CAPTURISTA', risk: 'NORMAL' },
  { id: 54, description: 'CARNICERO', risk: 'NORMAL' },
  { id: 55, description: 'CARPINTERO', risk: 'SUBNORMAL' },
  { id: 56, description: 'CARROCERO', risk: 'NORMAL' },
  { id: 57, description: 'CARTERO', risk: 'NORMAL' },
  { id: 58, description: 'CERRAJERO', risk: 'NORMAL' },
  { id: 59, description: 'CHEF', risk: 'NORMAL' },
  { id: 60, description: 'CHOFER / ESCOLTA CON PORTE DE ARMA', risk: 'SUBNORMAL' },
  { id: 61, description: 'CHOFER CAMIONETA TIPO VAN, AUTOBÚS, MICROBUS EN CD HASTA 3 TONELADAS', risk: 'NORMAL' },
  { id: 62, description: 'CHOFER DE AMBULANCIA O BOMBEROS', risk: 'SUBNORMAL' },
  { id: 63, description: 'CHOFER DE CAMIÓN DE BASURA', risk: 'NORMAL' },
  { id: 64, description: 'CHOFER DE CAMIÓN DE MÁS DE 20 TON FORANEO CON REMOLQUE (MAT NO PELIGROSO)', risk: 'SUBNORMAL' },
  { id: 65, description: 'CHOFER DE CAMIÓN DE MÁS DE 20 TON FORANEO CON REMOLQUE (MAT PELIGROSO)', risk: 'SUBNORMAL' },
  { id: 66, description: 'CHOFER DE CAMIÓN DE MÁS DE 20 TON LOCAL (MAT NO PELIGROSO)', risk: 'SUBNORMAL' },
  { id: 67, description: 'CHOFER DE CAMIÓN DE MÁS DE 20 TON LOCAL (MAT PELIGROSO)', risk: 'SUBNORMAL' },
  { id: 68, description: 'CHOFER DE CAMIÓN DE 3 HASTA 20 TON SIN REMOLQUE LOCAL (MAT NO PELIGROSO)', risk: 'NORMAL' },
  { id: 69, description: 'CHOFER DE CAMIÓN DE 3 HASTA 20 TON SIN REMOLQUE FORANEO(MAT NO PELIGROSO)', risk: 'SUBNORMAL' },
  { id: 70, description: 'CHOFER DE CAMIÓN DE 3 HASTA 20 TON SIN REMOLQUE FORANEO(MAT PELIGROSO)', risk: 'SUBNORMAL' },
  { id: 71, description: 'CHOFER DE CAMIÓN DE 3 HASTA 20 TON SIN REMOLQUE LOCAL (MAT PELIGROSO)', risk: 'SUBNORMAL' },
  { id: 72, description: 'CHOFER DE CAMIÓN PARA EL TRASLADO DE VALORES', risk: 'SUBNORMAL' },
  { id: 73, description: 'CHOFER DE GRÚA', risk: 'NORMAL' },
  { id: 74, description: 'CHOFER DE PATRULLA', risk: 'SUBNORMAL' },
  { id: 75, description: 'CHOFER DE PIPA CON MATERIAL PELIGROSO (GAS, DIESEL, ACIDOS, EXPLOSIVOS)', risk: 'SUBNORMAL' },
  { id: 76, description: 'CHOFER DE SERVICIOS URBANOS', risk: 'NORMAL' },
  { id: 77, description: 'CHOFER PARTICULAR', risk: 'NORMAL' },
  { id: 78, description: 'CHOFER REPARTIDOR DE GAS HASTA 3 TONELADAS', risk: 'SUBNORMAL' },
  { id: 79, description: 'CHOFER TAXI', risk: 'NORMAL' },
  { id: 80, description: 'CITOTECNÓLOGO', risk: 'SUBNORMAL' },
  { id: 81, description: 'COBRADOR (AUTOMOVIL)', risk: 'NORMAL' },
  { id: 82, description: 'COBRADOR (MOTO, BICI)', risk: 'NORMAL' },
  { id: 83, description: 'COBRADOR EN UBICACIÓN FIJA', risk: 'NORMAL' },
  { id: 84, description: 'COCINERO', risk: 'SUBNORMAL' },
  { id: 85, description: 'COLABORADOR ARGOS', risk: 'NORMAL' },
  { id: 86, description: 'COLOCADOR DE ANTENA', risk: 'SUBNORMAL' },
  { id: 87, description: 'COMENTARISTA', risk: 'NORMAL' },
  { id: 88, description: 'COMERCIANTE', risk: 'NORMAL' },
  { id: 89, description: 'CONSERJE', risk: 'NORMAL' },
  { id: 90, description: 'CONSULTOR', risk: 'NORMAL' },
  { id: 91, description: 'CONTADOR PÚBLICO', risk: 'NORMAL' },
  { id: 92, description: 'CONTRATISTA', risk: 'NORMAL' },
  { id: 93, description: 'CUSTODIO DE CARCEL O CELADOR', risk: 'SUBNORMAL' },
  { id: 94, description: 'CUSTODIO DE VALORES', risk: 'SUBNORMAL' },
  { id: 95, description: 'DECORADOR', risk: 'NORMAL' },
  { id: 96, description: 'DELEGADO SINDICAL', risk: 'SUBNORMAL' },
  { id: 97, description: 'DERMATÓLOGO', risk: 'SUBNORMAL' },
  { id: 98, description: 'DESARROLLADOR DE SISTEMAS', risk: 'NORMAL' },
  { id: 99, description: 'DESAZOLVE', risk: 'NORMAL' },
  { id: 100, description: 'DESPACHADOR DE FERRETERÍA', risk: 'NORMAL' },
  { id: 101, description: 'DISEÑADOR GRÁFICO', risk: 'NORMAL' },
  { id: 102, description: 'DISEÑO DE INTERIORES Y EXTERIORES (ADMINISTRATIVO)', risk: 'NORMAL' },
  { id: 103, description: 'DISEÑO DE INTERIORES Y EXTERIORES (PINTURA, YESO, PULIDOR)', risk: 'NORMAL' },
  { id: 104, description: 'DOCENTE', risk: 'NORMAL' },
  { id: 105, description: 'EJERCITO', risk: 'SUBNORMAL' },
  { id: 106, description: 'ELECTRICISTA INDUSTRIAL ALTA TENSIÓN LINEA MUERTA O VIVA', risk: 'SUBNORMAL' },
  { id: 107, description: 'ELECTRICISTA INDUSTRIAL HASTA 220 WATTS LINEA MUERTA', risk: 'NORMAL' },
  { id: 108, description: 'ELECTRICISTA INDUSTRIAL HASTA 220 WATTS LINEA VIVA', risk: 'SUBNORMAL' },
  { id: 109, description: 'ENFERMERO', risk: 'SUBNORMAL' },
  { id: 110, description: 'ESTILISTA', risk: 'NORMAL' },
  { id: 111, description: 'ESTOMATÓLOGO', risk: 'SUBNORMAL' },
  { id: 112, description: 'ESTUDIANTE', risk: 'NORMAL' },
  { id: 113, description: 'FARMACÉUTICO', risk: 'SUBNORMAL' },
  { id: 114, description: 'FARMACOBIÓLOGO', risk: 'SUBNORMAL' },
  { id: 115, description: 'FONTANERO', risk: 'NORMAL' },
  { id: 116, description: 'FOTÓGRAFO', risk: 'NORMAL' },
  { id: 117, description: 'FUMIGADOR DE JARDÍN', risk: 'NORMAL' },
  { id: 118, description: 'GANADERO (COMPRA Y VENTA GANADO)', risk: 'NORMAL' },
  { id: 119, description: 'GUARDIA DE SEGURIDAD CON ARMA', risk: 'SUBNORMAL' },
  { id: 120, description: 'HERRERO', risk: 'SUBNORMAL' },
  { id: 121, description: 'INGENIERO', risk: 'NORMAL' },
  { id: 122, description: 'INGENIERO CIVIL', risk: 'NORMAL' },
  { id: 123, description: 'INGENIERO ELECTROMECÁNICO', risk: 'NORMAL' },
  { id: 124, description: 'INHALOTERAPEUTA', risk: 'SUBNORMAL' },
  { id: 125, description: 'INSPECTOR', risk: 'NORMAL' },
  { id: 126, description: 'INSTRUCTOR CANINO', risk: 'NORMAL' },
  { id: 127, description: 'INSTRUCTOR DE GIMNASIO', risk: 'NORMAL' },
  { id: 128, description: 'INSTRUCTOR DE NATACIÓN', risk: 'NORMAL' },
  { id: 129, description: 'INSTRUCTOR DE PARACAIDISMO', risk: 'SUBNORMAL' },
  { id: 130, description: 'INTENDENCIA', risk: 'SUBNORMAL' },
  { id: 131, description: 'INVESTIGADOR ACADÉMICO', risk: 'NORMAL' },
  { id: 132, description: 'JARDINERO', risk: 'NORMAL' },
  { id: 133, description: 'JUBILADO', risk: 'SUBNORMAL' },
  { id: 134, description: 'JUEZ FEDERAL', risk: 'SUBNORMAL' },
  { id: 135, description: 'JUEZ LOCAL', risk: 'NORMAL' },
  { id: 136, description: 'LABORATORISTA', risk: 'SUBNORMAL' },
  { id: 137, description: 'LABORES DEL HOGAR', risk: 'NORMAL' },
  { id: 138, description: 'LAVANDERA DE HOSPITAL', risk: 'SUBNORMAL' },
  { id: 139, description: 'LIMPIA DE CISTERNA O CAÑERÍA', risk: 'NORMAL' },
  { id: 140, description: 'LIMPIEZA DE HOGAR', risk: 'NORMAL' },
  { id: 141, description: 'LIMPIEZA DE PANTEÓN', risk: 'SUBNORMAL' },
  { id: 142, description: 'LIMPIEZA DE VIDRIOS EN EMPRESA', risk: 'NORMAL' },
  { id: 143, description: 'LIMPIEZA DE VIDRIOS POR CUENTA PROPIA', risk: 'SUBNORMAL' },
  { id: 144, description: 'LIMPIEZA URBANA Y ÁREAS VERDES', risk: 'NORMAL' },
  { id: 145, description: 'MÉDICO', risk: 'SUBNORMAL' },
  { id: 146, description: 'MACHETERO', risk: 'SUBNORMAL' },
  { id: 147, description: 'MAESTRO DE BAILE', risk: 'NORMAL' },
  { id: 148, description: 'MAESTRO DE OBRAS', risk: 'NORMAL' },
  { id: 149, description: 'MAGISTRADO', risk: 'SUBNORMAL' },
  { id: 150, description: 'MANT GRAL (ALBAÑILERIA, SOLDADORES, CARPINTERIOS, HERREROS, MACHETERIOS Y ELECTRICIDAD MAS DE 220 WATS LINEA VIVA)', risk: 'SUBNORMAL' },
  { id: 151, description: 'MANT GRAL (LIMPIEZA DOMESTICA, BACHEO, DESAZOLVE. JARDINERÍA, FUMIGADOR EN TIERRA DE JARDINES)', risk: 'NORMAL' },
  { id: 152, description: 'MANT GRAL (PINTAR, RESANAR, PLOMERIA, PULIDOR, CISTERNAS, PEON DE LIMPIA Y ELECTRICIDAD HASTA 220 WATS LINEA MUERTA )', risk: 'NORMAL' },
  { id: 153, description: 'MANT GRAL (TRENES, MAQUINARIA PESADA, HORNOS ALTAS TEMPERATURAS, ELEVADORES Y ELECTRICIDAD ALTA TENSIÓN)', risk: 'SUBNORMAL' },
  { id: 154, description: 'MARINOS', risk: 'SUBNORMAL' },
  { id: 155, description: 'MECÁNICO', risk: 'NORMAL' },
  { id: 156, description: 'MECANÓGRAFO DEL MP', risk: 'SUBNORMAL' },
  { id: 157, description: 'MENSAJERO (AUTOMOVIL)', risk: 'NORMAL' },
  { id: 158, description: 'MENSAJERO (INTRAMUROS)', risk: 'NORMAL' },
  { id: 159, description: 'MENSAJERO (MOTO O BICICLETA)', risk: 'NORMAL' },
  { id: 160, description: 'MESERO', risk: 'NORMAL' },
  { id: 161, description: 'MOZO', risk: 'NORMAL' },
  { id: 162, description: 'MÚSICO', risk: 'NORMAL' },
  { id: 163, description: 'NUTRICIONISTA', risk: 'SUBNORMAL' },
  { id: 164, description: 'OBRERO DE ELABORACIÓN DE ALIMENTOS', risk: 'SUBNORMAL' },
  { id: 165, description: 'OBRERO DE ELABORACIÓN DE PAPEL, PIEZAS DE CAUCHO O PLASTICO (HORNOS A ALTAS TEMPERATURAS)', risk: 'SUBNORMAL' },
  { id: 166, description: 'OBRERO DE ENSAMBLE DE PIEZAS O ARNESES MANUAL', risk: 'NORMAL' },
  { id: 167, description: 'OBREROS EN SIDERURGICAS, CEMENTERAS, MINERAS Y PLATAFORMAS PETROLERAS', risk: 'SUBNORMAL' },
  { id: 168, description: 'OFICIAL DE OPERACIONES DE AERONAVES EN AEROPUERTO', risk: 'NORMAL' },
  { id: 169, description: 'OFTALMÓLOGO', risk: 'SUBNORMAL' },
  { id: 170, description: 'OPERADOR DE MONTACARGAS', risk: 'NORMAL' },
  { id: 171, description: 'OPERARIO DE AIRE ACONDICIONADO INDUSTRIAL', risk: 'NORMAL' },
  { id: 172, description: 'OPERARIO DE AIRE ACONDICIONADO RESIDENCIAL', risk: 'NORMAL' },
  { id: 173, description: 'PANADERO', risk: 'NORMAL' },
  { id: 174, description: 'PANTEONERO', risk: 'SUBNORMAL' },
  { id: 175, description: 'PARAMÉDICO', risk: 'SUBNORMAL' },
  { id: 176, description: 'PEDAGOGA', risk: 'NORMAL' },
  { id: 177, description: 'PERITO ADMINISTRATIVO', risk: 'NORMAL' },
  { id: 178, description: 'PERITO EN CAMPO', risk: 'SUBNORMAL' },
  { id: 179, description: 'PEÓN DE LIMPIA', risk: 'NORMAL' },
  { id: 180, description: 'PILOTO DE AEROLÍNEA COMERCIAL', risk: 'SUBNORMAL' },
  { id: 181, description: 'PINTOR', risk: 'NORMAL' },
  { id: 182, description: 'PLOMERO', risk: 'NORMAL' },
  { id: 183, description: 'POLICÍA', risk: 'SUBNORMAL' },
  { id: 184, description: 'PREFECTO', risk: 'NORMAL' },
  { id: 185, description: 'PRESIDENTE MUNICIPAL', risk: 'NORMAL' },
  { id: 186, description: 'PSICÓLOGO', risk: 'SUBNORMAL' },
  { id: 187, description: 'PULIDORES', risk: 'SUBNORMAL' },
  { id: 188, description: 'QUÍMICO', risk: 'SUBNORMAL' },
  { id: 189, description: 'RECAMARERA', risk: 'NORMAL' },
  { id: 190, description: 'RECEPCIONISTA', risk: 'NORMAL' },
  { id: 191, description: 'RECOLECTOR DE BASURA', risk: 'NORMAL' },
  { id: 192, description: 'REGIDOR', risk: 'NORMAL' },
  { id: 193, description: 'SALVAVIDAS', risk: 'SUBNORMAL' },
  { id: 194, description: 'SECRETARIO DEL MP', risk: 'SUBNORMAL' },
  { id: 195, description: 'SOLDADORES', risk: 'SUBNORMAL' },
  { id: 196, description: 'TÉCNICO RADIÓLOGO', risk: 'SUBNORMAL' },
  { id: 197, description: 'TAPICERO', risk: 'NORMAL' },
  { id: 198, description: 'TELEFONISTA', risk: 'NORMAL' },
  { id: 199, description: 'TERAPEUTA', risk: 'SUBNORMAL' },
  { id: 200, description: 'TERAPISTA DE LENGUAJE', risk: 'SUBNORMAL' },
  { id: 201, description: 'TOPÓGRAFO', risk: 'NORMAL' },
  { id: 202, description: 'TRABAJADOR SOCIAL', risk: 'SUBNORMAL' },
  { id: 203, description: 'VELADOR CON ARMA', risk: 'SUBNORMAL' },
  { id: 204, description: 'VELADOR SIN ARMA', risk: 'NORMAL' },
  { id: 205, description: 'VIGILANTE CON ARMA', risk: 'SUBNORMAL' },
  { id: 206, description: 'VIGILANTE SIN ARMA', risk: 'NORMAL' },
  { id: 207, description: 'YESERO - AZULEJERO', risk: 'NORMAL' },
  { id: 208, description: 'ZAPATERO', risk: 'NORMAL' },
  { id: 209, description: 'FUERZAS ARMADAS', risk: 'SUBNORMAL' },
  { id: 210, description: 'PROTECCIÓN CIVIL Y/O VOLUNTARIOS EN COMUNIDADES', risk: 'SUBNORMAL' },
  { id: 211, description: 'GUIA DE TURISTAS', risk: 'SUBNORMAL' },
  { id: 212, description: 'ADMINISTRATIVO', risk: 'NORMAL' },
  { id: 213, description: 'EDUCACIÓN', risk: 'NORMAL' },
  { id: 214, description: 'LIMPIEZA', risk: 'NORMAL' },
  { id: 215, description: 'MANTENIMIENTO', risk: 'NORMAL' },
  { id: 216, description: 'SALUD', risk: 'NORMAL' }
];


const catalogs = {
  PARTICIPATING_BANKS: [
    { id: 1, value: 'BANCOMER' },
    { id: 2, value: 'BBVA' },
    { id: 3, value: 'SANTANDER' },
    { id: 3, value: 'HSBC' },
    { id: 5, value: 'OTHER' },
  ],
  // New Catalog: DANGEROUS_SPORTS
  DANGEROUS_SPORTS: [
    { id: 1, value: 'Box' },
    { id: 2, value: 'Bungee Jumping' },
    { id: 3, value: 'Carrera de caballos' },
    { id: 4, value: 'Carreras de vehículos c/motor' },
    { id: 5, value: 'Charrería' },
    { id: 6, value: 'Esquí' },
    { id: 7, value: 'Inmersión submarina' },
    { id: 8, value: 'Lanchas' },
    { id: 9, value: 'Lucha libre' },
    { id: 10, value: 'Montañismo' },
    { id: 11, value: 'Motociclismo' },
    { id: 12, value: 'Motocross' },
    { id: 13, value: 'Paracaidismo' },
    { id: 14, value: 'Parapente' },
    { id: 15, value: 'Parkour' },
    { id: 16, value: 'Pesca deportiva' },
    { id: 17, value: 'Rafting' },
    { id: 18, value: 'Rappel' },
    { id: 19, value: 'Surfing' },
    { id: 20, value: 'Tauromaquia' },
    { id: 21, value: 'Vuelo Delta' },
  ],
  // New Catalog: STATES
  STATES: [
    { id: 1, value: 'AGUASCALIENTES' },
    { id: 2, value: 'BAJA CALIFORNIA' },
    { id: 3, value: 'BAJA CALIFORNIA SUR' },
    { id: 4, value: 'CAMPECHE' },
    { id: 5, value: 'COAHUILA' },
    { id: 6, value: 'COLIMA' },
    { id: 7, value: 'CHIAPAS' },
    { id: 8, value: 'CHIHUAHUA' },
    { id: 9, value: 'CIUDAD DE MÉXICO' },
    { id: 10, value: 'DURANGO' },
    { id: 11, value: 'GUANAJUATO' },
    { id: 12, value: 'GUERRERO' },
    { id: 13, value: 'HIDALGO' },
    { id: 14, value: 'JALISCO' },
    { id: 15, value: 'ESTADO DE MÉXICO' },
    { id: 16, value: 'MICHOACÁN' },
    { id: 17, value: 'MORELOS' },
    { id: 18, value: 'NAYARIT' },
    { id: 19, value: 'NUEVO LEÓN' },
    { id: 20, value: 'OAXACA' },
    { id: 21, value: 'PUEBLA' },
    { id: 22, value: 'QUERÉTARO' },
    { id: 23, value: 'QUINTANA ROO' },
    { id: 24, value: 'SAN LUIS POTOSÍ' },
    { id: 25, value: 'SINALOA' },
    { id: 26, value: 'SONORA' },
    { id: 27, value: 'TABASCO' },
    { id: 28, value: 'TAMAULIPAS' },
    { id: 29, value: 'TLAXCALA' },
    { id: 30, value: 'VERACRUZ' },
    { id: 31, value: 'YUCATÁN' },
    { id: 32, value: 'ZACATECAS' },
  ],
  // New Catalog: KINSHIP
  KINSHIP: [
    { id: 1, value: 'ABUELA' },
    { id: 2, value: 'ABUELO' },
    { id: 3, value: 'CONCUBINA' },
    { id: 4, value: 'CONCUBINO' },
    { id: 5, value: 'CONYUGE' },
    { id: 6, value: 'CUÑADA' },
    { id: 7, value: 'CUÑADO' },
    { id: 8, value: 'HERMANA' },
    { id: 9, value: 'HERMANO' },
    { id: 10, value: 'HIJA' },
    { id: 11, value: 'HIJASTRA' },
    { id: 12, value: 'HIJASTRO' },
    { id: 13, value: 'HIJO' },
    { id: 14, value: 'MADRE' },
    { id: 15, value: 'NIETA' },
    { id: 16, value: 'NIETO' },
    { id: 17, value: 'NINGUNO' },
    { id: 18, value: 'PADRE' },
    { id: 19, value: 'PRIMA' },
    { id: 20, value: 'PRIMO' },
    { id: 21, value: 'SOBRINA' },
    { id: 22, value: 'SOBRINO' },
    { id: 23, value: 'SUEGRA' },
    { id: 24, value: 'SUEGRO' },
    { id: 25, value: 'TIA' },
    { id: 26, value: 'TIO' },
  ],
  // New Catalog: BANNED_COUNTRIES
  BANNED_COUNTRIES: [
    { id: 1, value: 'Irán' },
    { id: 2, value: 'Bahamas' },
    { id: 3, value: 'Bostwana' },
    { id: 4, value: 'Camboya' },
    { id: 5, value: 'Etiopía' },
    { id: 6, value: 'Ghana' },
    { id: 7, value: 'Pakistán' },
    { id: 8, value: 'Panamá' },
    { id: 9, value: 'Siria' },
    { id: 10, value: 'Sri Lanka' },
    { id: 11, value: 'Trinidad y Tobago' },
    { id: 12, value: 'Túnez' },
    { id: 13, value: 'Yemen' },
  ],
  // New Catalog: COUNTRIES
  COUNTRIES: [
    { id: 1, value: 'United States' },
    { id: 2, value: 'China' },
    { id: 3, value: 'Japan' },
    { id: 4, value: 'Germany' },
    { id: 5, value: 'United Kingdom' },
    { id: 6, value: 'France' },
    { id: 7, value: 'India' },
    { id: 8, value: 'Italy' },
    { id: 9, value: 'Brazil' },
    { id: 10, value: 'Canada' },
    { id: 11, value: 'Russia' },
    { id: 12, value: 'Australia' },
    { id: 13, value: 'South Korea' },
    { id: 14, value: 'Spain' },
    { id: 15, value: 'Mexico' },
    { id: 16, value: 'Indonesia' },
    { id: 17, value: 'Netherlands' },
    { id: 18, value: 'Saudi Arabia' },
    { id: 19, value: 'Turkey' },
    { id: 20, value: 'Switzerland' },
    { id: 21, value: 'Argentina' },
    { id: 22, value: 'Sweden' },
    { id: 23, value: 'Belgium' },
    { id: 24, value: 'Poland' },
    { id: 25, value: 'Thailand' },
    { id: 26, value: 'Guatemala' },
    { id: 27, value: 'Belize' },
  ],
  // Add other catalog types as needed
};

const plans = [
  // New Plan: BASICO (PLAN100)
  {
    id: '001',
    productName: 'PLAN100',
    fullName: 'BASICO',
    paymentMethods: [
      { paymentMethod: 'MENSUAL', premium: 100.0 },
      { paymentMethod: 'ANUAL', premium: 1200.0 },
    ],
    coverages: [
      { name: 'FALLECIMIENTO', insuredAmount: 100000.0 },
      { name: 'MUERTE ACCIDENTAL', insuredAmount: 100000.0 },
      { name: 'ANTICIPO PARA GASTOS INMEDIATOS', insuredAmount: 25000.0 },
      { name: 'ANTICIPO POR ENFERMEDAD TERMINAL', insuredAmount: 0.0 },
    ],
  },
  // New Plan: PREMIUM (PLAN500)
  {
    id: '002',
    productName: 'PLAN500',
    fullName: 'PREMIUM',
    paymentMethods: [
      { paymentMethod: 'MENSUAL', premium: 250.0 },
      { paymentMethod: 'ANUAL', premium: 2700.0 },
    ],
    coverages: [
      { name: 'FALLECIMIENTO', insuredAmount: 500000.0 },
      { name: 'MUERTE ACCIDENTAL', insuredAmount: 250000.0 },
      { name: 'SUMA ASEGURADA POR INVALIDEZ TOTAL Y PERMANENTE', insuredAmount: 250000.0 },
      { name: 'GRAVES ENFERMEDADES', insuredAmount: 250000.0 },
      { name: 'ANTICIPO POR ENFERMEDAD TERMINAL', insuredAmount: 0.0 },
    ],
  },
];

const postalCodes = {
  '57000': {
    municipality: 'Nezahualcoyotl',
    city: 'Nezahualcoyotl',
    state: 'Mexico',
    country: 'Mexico',
    neighborhoods: ['Benito Juarez', 'Centro'],
  },
  // Add other postal codes as needed
};

exports.getOccupationsList = (req, res) => {
  res.json(occupations);
};

exports.getCatalogs = (req, res) => {
  const { catalogType } = req.query;
  const catalog = catalogs[catalogType];
  if (!catalog) {
    return res.status(400).json({ status: false, message: 'Invalid catalog type' });
  }
  res.json(catalog);
};

exports.getPlans = (req, res) => {
  res.json({ plans });
};

exports.getLocationByPostalCode = (req, res) => {
  const { postalCode } = req.params;
  const location = postalCodes[postalCode];
  if (!location) {
    return res.status(404).json({ status: false, message: 'Postal code not found' });
  }
  res.json(location);
};
